In [1]:
import numpy as np

In [2]:
my_list = [[1,2], [3,4]]
np.array(my_list)

array([[1, 2],
       [3, 4]])

In [3]:
np.array(my_list, dtype=np.float16)

array([[1., 2.],
       [3., 4.]], dtype=float16)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
#Create an equally spaced Numpy Array with a specific step
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(3,40)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [9]:
np.arange(3,40,6)

array([ 3,  9, 15, 21, 27, 33, 39])

In [10]:
#Create an equally spaced Numpy Array with a specific array size
np.linspace(start=5, stop=20, num=10)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [11]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
#Generate a random numpy array
np.random.randint(low=5, high=25, size=10)

array([14, 20, 15, 24, 17, 20, 23,  8, 24, 23])

In [13]:
np.random.randint(10,20,2)

array([17, 11])

In [14]:
## 2 NumPy Array Manipulation Methods

In [15]:
#Shape of the NumPy Array
a = np.ones((2,5))
print("shape of array:", np.shape(a))
print("shape of array", a.shape)

shape of array: (2, 5)
shape of array (2, 5)


In [16]:
#Reshape the NumPy Array
a = np.arange(10).reshape(10,)
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
#Transpose the NumPy Array
np.arange(10).reshape(2,5).transpose().T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
#Concatenate multiple NumPy arrays to form one NumPy Array
a = np.array([[1,2], [2,4]])
b = np.array([[5,8]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [2, 4, 8]])

In [19]:
#Masked Array
a = np.ma.arange(3)
a[1] = np.ma.masked
a

masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)

In [20]:
arrays = [np.random.randn(3,4) for _ in range(10)]
np.stack(arrays, axis=1)

array([[[-0.07583484,  0.80154441, -1.70320864, -0.06714538],
        [ 1.27592054, -0.24675408,  1.76579485, -0.74736535],
        [-0.15315054,  0.02104215, -1.73558327,  0.40127252],
        [-1.29358174,  1.54443641,  0.50930785,  0.93513483],
        [-0.17772741, -1.13509831, -0.06766208,  0.36329318],
        [ 0.17351197, -1.67460792, -1.03756474, -1.08841911],
        [-0.27861253, -0.0817309 ,  1.78512496,  0.53718989],
        [-0.64101176,  0.68286141,  0.24659929, -0.03392345],
        [-0.70285417,  0.1217731 , -1.37749861,  1.27137213],
        [ 1.04074269,  1.49339026,  0.81495181,  0.01923235]],

       [[ 1.26606104, -0.27985141, -0.63832478, -0.82269995],
        [ 1.52915923, -0.37755322, -0.47657325,  0.73179515],
        [-0.31153187, -0.63785027,  0.88152515,  0.12023444],
        [ 0.48584899,  0.98025664, -0.83513825,  0.88558014],
        [-0.49966316, -0.24006039,  2.05797921, -0.43874642],
        [ 0.22666417,  0.04316207, -1.71585673, -0.04559733],
      