In [1]:
import numpy as np

In [8]:
my_list = [[1,2], [3,4]]
np.array(my_list)

array([[1, 2],
       [3, 4]])

In [9]:
np.array(my_list, dtype=np.float16)

array([[1., 2.],
       [3., 4.]], dtype=float16)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
#Create an equally spaced Numpy Array with a specific step
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(3,40)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [16]:
np.arange(3,40,6)

array([ 3,  9, 15, 21, 27, 33, 39])

In [17]:
#Create an equally spaced Numpy Array with a specific array size
np.linspace(start=5, stop=20, num=10)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [18]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [20]:
#Generate a random numpy array
np.random.randint(low=5, high=25, size=10)

array([12,  5,  6, 21,  8,  7, 14,  7, 23, 13])

In [21]:
np.random.randint(10,20,2)

array([14, 17])

In [24]:
## 2 NumPy Array Manipulation Methods

In [26]:
#Shape of the NumPy Array
a = np.ones((2,5))
print("shape of array:", np.shape(a))
print("shape of array", a.shape)

shape of array: (2, 5)
shape of array (2, 5)


In [28]:
#Reshape the NumPy Array
a = np.arange(10).reshape(10,)
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
#Transpose the NumPy Array
np.arange(10).reshape(2,5).transpose().T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
#Concatenate multiple NumPy arrays to form one NumPy Array
a = np.array([[1,2], [2,4]])
b = np.array([[5,8]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [2, 4, 8]])